// Automatically generated by rust_swig
package com.schuetz.rust_android_ios;
import android.support.annotation.NonNull;

public final class MyRustStruct {

    public MyRustStruct() {
        mNativeObj = init();
    }
    private static native long init();

    public final int add(int val) {
        int ret = do_add(mNativeObj, val);

        return ret;
    }
    private static native int do_add(long self, int val);

    public final @NonNull String greet(@NonNull String to) {
        String ret = do_greet(mNativeObj, to);

        return ret;
    }
    private static native @NonNull String do_greet(long self, @NonNull String to);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MyRustStruct(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}